baseurl = "/"
title = "Noah Landesberg"
author = "Noah Landesberg"
relativeurls = true
canonifyurls = true
languagecode = "en"
paginate = 3
theme = "hugo-renga"

enableEmoji = true
hasCJKLanguage = true

googleAnalytics = "UA-108370158-1"
disableKinds = ["taxonomy", "taxonomyTerm"]
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
pagetitle = "Noah Landesberg"
copyright = "© 2020 Noah Landesberg"
copyrightUrl = "https://www.noahlandesberg.com"
faviconfile = "image/favicon.png"
logofile = "image/avatar.jpg"
posts_navigation = true
uselatex = true
highlightjs = true
progressively = true

github = "landesbergn"
twitter = "noahlandesberg"
linkedin = "noah-landesberg"
email = "noah.landesberg@gmail.com"

[[menu.primary]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 1

[[menu.primary]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 2
