baseurl = "/"
title = "Noah Landesberg"
author = "Noah Landesberg"
relativeurls = true
canonifyurls = true
languagecode = "en"
paginate = 3
theme = "hugo-renga"

enableEmoji = true
hasCJKLanguage = true

googleAnalytics = "UA-108370158-1"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
pagetitle = "Noah Landesberg"
copyright = "© 2019 Noah Landesberg"
copyrightUrl = "https://www.noahlandesberg.com"
faviconfile = "image/favicon.png"
logofile = "image/avatar.jp2"
posts_navigation = true
uselatex = true
highlightjs = true
progressively = false

github = "landesbergn"
twitter = "noahlandesberg"
linkedin = "noah-landesberg"
email = "noah.landesberg@gmail.com"

[[menu.primary]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 1

[[menu.primary]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 2
